server:
  port: 8080

spring:
  application:
    name: 'vending machine'

  datasource:
    username: flapkap
    password: password
    url: jdbc:postgresql://localhost:5433/flapkap
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true